import Image from 'next/image'

export function ScreenshotsSection() {
  return (
    <section id="screenshots" className="py-16 md:py-24 bg-white">
      <div className="container px-4 md:px-6 mx-auto max-w-6xl">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl font-bold tracking-tight mb-4 text-slate-900 sm:text-4xl">Product Screenshots</h2>
          <p className="text-xl text-slate-600 max-w-3xl mx-auto">
            A quick look at ITPs and plans generated by AI, plus day‑to‑day Lots, NCRs, and drawings management.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8">
          {[
            { src: '/screenshots/user/user-screenshot-1.png', alt: 'User screenshot 1' },
            { src: '/screenshots/user/user-screenshot-2.png', alt: 'User screenshot 2' },
            { src: '/screenshots/user/user-screenshot-3.png', alt: 'User screenshot 3' },
          ].map((shot) => (
            <div key={shot.src} className="bg-slate-50 border border-slate-200 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition">
              <div className="relative w-full" style={{ aspectRatio: '16 / 10' }}>
                <Image src={shot.src} alt={shot.alt} fill sizes="(min-width: 1024px) 33vw, 100vw" className="object-cover" />
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}



